apiVersion: sample.template.crossplane.io/v1alpha1
kind: MyType
metadata:
  name: example
spec:
  forProvider:
    nodeAddress: test
    resourceToDownload: test
  providerConfigRef:
    name: default