apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-template
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane/provider-template
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A template that can be used to create Crossplane providers.
spec:
  ignoreCrossplaneConstraints: true
  package: docker.io/datavix/prova
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
    # permissionRequests:
    # - apiGroups:
    #   - apiextensions.crossplane.io
    #   resources:
    #   - compositions
    #   verbs:
    #   - get
    #   - list
    #   - create
    #   - update
    #   - patch
    #   - watch
    # registry.gitlab.com/sabbio93/slicesansible:VERSION